apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: static-server
  name: static-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: static-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: static-server
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          resources:
            requests:
              memory: {{ .Values.nginx.resources.requests.memory }}
              cpu: {{ .Values.nginx.resources.requests.cpu }}
            limits:
              memory: {{ .Values.nginx.resources.limits.memory }}
              cpu: {{ .Values.nginx.resources.limits.cpu }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      initContainers: []
      volumes:
        - name: config-volume
          configMap:
            name: static-server