apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: static-server
  name: static-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: static-server